workflows:
  shell-gjilan-ipa:
    name: Shell Gjilan IPA
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter packages
        script: |
          flutter pub get

      - name: CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS Release unsigned
        script: |
          flutter build ios --release --no-codesign

      - name: Create IPA
        script: |
          rm -rf build/ios/ipa_unsigned
          mkdir -p build/ios/ipa_unsigned/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa_unsigned/Payload/
          cd build/ios/ipa_unsigned
          /usr/bin/zip -qry ShellGjilan.ipa Payload

    artifacts:
      - build/ios/ipa_unsigned/ShellGjilan.ipa
      - /tmp/xcodebuild_logs/*.log
