class AppStrings {
  AppStrings._();

  static String t(String key, String lang) {
    final map = lang == 'en' ? _en : _sq;
    return map[key] ?? _sq[key] ?? key;
  }

  static const _sq = <String, String>{
    'appName': 'Shell Gjilan',
    'subtitle': 'Menaxhimi i artikujve',
    'login': 'Kyçu',
    'username': 'Përdoruesi',
    'password': 'Fjalëkalimi',
    'loginHint': 'Përdor të njëjtën llogari si në web.',
    'dashboard': 'Dashboard',
    'articles': 'Artikujt',
    'orders': 'Porositë',
    'statistics': 'Statistikat',
    'settings': 'Cilësimet',
    'total': 'Gjithsej',
    'expired': 'Të skaduar',
    'today': 'Skadojnë sot',
    'expiring': 'Brenda 30 ditëve',
    'active': 'Aktivë',
    'suppliers': 'Furnitorë',
    'refresh': 'Rifresko',
    'search': 'Kërko artikull, barcode, furnitor...',
    'all': 'Të gjitha',
    'addArticle': 'Shto artikull',
    'editArticle': 'Ndrysho artikullin',
    'delete': 'Fshi',
    'edit': 'Ndrysho',
    'name': 'Emri',
    'barcode': 'Barkodi',
    'supplier': 'Furnitori',
    'quantity': 'Sasia',
    'expiryDate': 'Data e skadimit',
    'save': 'Ruaj',
    'cancel': 'Anulo',
    'days': 'ditë',
    'noArticles': 'Nuk u gjet asnjë artikull.',
    'noOrders': 'Nuk ka porosi.',
    'client': 'Klienti',
    'date': 'Data',
    'items': 'Artikuj',
    'addOrder': 'Shto porosi',
    'unit': 'Njësia',
    'addLine': 'Shto rresht',
    'remove': 'Hiq',
    'supplierStats': 'Statistika sipas furnitorëve',
    'language': 'Gjuha',
    'appearance': 'Pamja',
    'system': 'Sistemi',
    'light': 'Light',
    'dark': 'Dark',
    'logout': 'Dil nga llogaria',
    'role': 'Roli',
    'admin': 'Admin',
    'worker': 'Punëtor',
    'connectionError': 'Nuk mund të lidhemi me serverin.',
    'confirmDelete': 'A je i sigurt që dëshiron ta fshish?',
    'yesDelete': 'Po, fshije',
    'required': 'Fushë e detyrueshme',
    'positiveNumber': 'Duhet numër pozitiv',
    'invalidDate': 'Përdor formatin YYYY-MM-DD',
    'sessionExpired': 'Sesioni ka skaduar. Kyçu përsëri.',
    'welcome': 'Mirë se erdhe',
    'overview': 'Përmbledhje e gjendjes aktuale',
    'retry': 'Provo përsëri',
    'server': 'Serveri',
    'online': 'Online',
    'status': 'Statusi',
  };

  static const _en = <String, String>{
    'appName': 'Shell Gjilan',
    'subtitle': 'Inventory management',
    'login': 'Sign in',
    'username': 'Username',
    'password': 'Password',
    'loginHint': 'Use the same account as the web panel.',
    'dashboard': 'Dashboard',
    'articles': 'Articles',
    'orders': 'Orders',
    'statistics': 'Statistics',
    'settings': 'Settings',
    'total': 'Total',
    'expired': 'Expired',
    'today': 'Expire today',
    'expiring': 'Within 30 days',
    'active': 'Active',
    'suppliers': 'Suppliers',
    'refresh': 'Refresh',
    'search': 'Search article, barcode, supplier...',
    'all': 'All',
    'addArticle': 'Add article',
    'editArticle': 'Edit article',
    'delete': 'Delete',
    'edit': 'Edit',
    'name': 'Name',
    'barcode': 'Barcode',
    'supplier': 'Supplier',
    'quantity': 'Quantity',
    'expiryDate': 'Expiry date',
    'save': 'Save',
    'cancel': 'Cancel',
    'days': 'days',
    'noArticles': 'No articles found.',
    'noOrders': 'No orders found.',
    'client': 'Client',
    'date': 'Date',
    'items': 'Items',
    'addOrder': 'Add order',
    'unit': 'Unit',
    'addLine': 'Add line',
    'remove': 'Remove',
    'supplierStats': 'Statistics by supplier',
    'language': 'Language',
    'appearance': 'Appearance',
    'system': 'System',
    'light': 'Light',
    'dark': 'Dark',
    'logout': 'Sign out',
    'role': 'Role',
    'admin': 'Admin',
    'worker': 'Worker',
    'connectionError': 'Could not connect to the server.',
    'confirmDelete': 'Are you sure you want to delete this?',
    'yesDelete': 'Yes, delete',
    'required': 'Required field',
    'positiveNumber': 'Must be a positive number',
    'invalidDate': 'Use YYYY-MM-DD format',
    'sessionExpired': 'Session expired. Please sign in again.',
    'welcome': 'Welcome',
    'overview': 'Current overview',
    'retry': 'Retry',
    'server': 'Server',
    'online': 'Online',
    'status': 'Status',
  };
}
